application: djae-endpoints-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: django
  version: 1.4

# Needed for endpoints/users_id_token.py.
- name: pycrypto
  version: 2.6

- name: endpoints
  version: 1.0

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: blog/static
  expiration: '1m'

# Endpoints handler
- url: /_ah/spi/.*
  script: blog.api.application

- url: /appengine_sessions/clean-up/
  script: main.app
  login: admin

- url: /admin/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app.yaml
- ^(.*/)?app.yml
- ^(.*/)?index.yaml
- ^(.*/)?index.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- tmp
